server.port=8081
spring.application.name=backend-pnm


# 1. Configuration de la connexion PostgreSQL
# Le port par défaut est 5432. Remplacez "votre_mot_de_passe" par le vôtre.
spring.datasource.url=jdbc:postgresql://localhost:5432/PDB_base
spring.datasource.username=postgres
spring.datasource.password=postgres

# 2. Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=admin
spring.security.user.password=pass123